### ISSUE TITLE
No Eval Scripts

### ISSUE THREAD

**Issue by JK-ho** [qingzhenduyu/TAMER#1]
Hello Sir, could  you please upload the eval scripts for CHROME ?

**Comment by BFlameSwift** [comment]
Hello,

Thank you for your request. I have added the eval scripts in the latest commit. Please check the updated repository.

If you have any further questions, feel free to ask.

**Comment by JK-ho** [comment]
Thankyou so much @BFlameSwift .
I'm getting following error while running -conda install pytorch=1.8.1 torchvision=0.2.2 cudatoolkit=11.1 pillow=8.4.0 -c pytorch -c nvidia

Channels:
 - pytorch
 - nvidia
 - defaults
Platform: linux-64
Collecting package metadata (repodata.json): done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

- torchvision=0.2.2

Current channels:

  - https://conda.anaconda.org/pytorch
  - https://conda.anaconda.org/nvidia
  - defaults

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

**Comment by BFlameSwift** [comment]
It seems that torchvision=0.2.2 is not available in the specified channels. Here’s an alternative way to set up the environment that should work for your project. Please follow these steps:

``` bash
conda create -y -n TAMER python=3.7
conda activate TAMER
conda install pytorch=1.8.1 cudatoolkit=11.1 pillow=8.4.0 -c pytorch -c nvidia
pip install torchvision==0.2.2
# training dependency
conda install pytorch-lightning=1.4.9 torchmetrics=0.6.0 -c conda-forge
# evaluating dependency
conda install pandoc=1.19.2.1 -c conda-forge
pip install -e .

```


This approach installs torchvision==0.2.2 via pip as it’s not available via conda in the version you’re looking for. Additionally, it ensures all training and evaluation dependencies are correctly installed.

Let me know if this works for you!

**Comment by JK-ho** [comment]
torchvision=0.9.1 is working for me now.

**Comment by KavitaM20AIE244** [comment]
Hello Sir,

could you please upload lightning_logs/version_1 checkpoint file please?
