### ISSUE TITLE
Missing lightning_logs/version_1

### ISSUE THREAD

**Issue by JK-ho** [qingzhenduyu/TAMER#2]
Hello Sir,

could you please upload lightning_logs/version_1 checkpoint file please?

**Comment by xiaoxiaoli666** [comment]
hello,I find version_0 is updated by the author,why do you need version_1?version_1 has some different thing?

**Comment by qingzhenduyu** [comment]
> Hello Sir,
> 
> could you please upload lightning_logs/version_1 checkpoint file please?

OK, I will upload the version_1 ckpt later. We have also incorporated a fusion module inspired by [ICAL](https://github.com/qingzhenduyu/ICAL) along with additional experiments. The results on the HME100K and CROHME datasets have shown significant improvement. We will release these results and the corresponding checkpoint files in the near future.

**Comment by qingzhenduyu** [comment]
@JK-ho Hi, the version_1 ckpt has been uploaded.
